### ISSUE TITLE
Potreboval by som poradit

### ISSUE THREAD

**Issue by okuliarjakub** [vitasrutek/CUZK-scraper#1]
Dobrý den, velmi si vážim program ktory ste vytvroili, pokial to spojaznim bude to neskutocna pomoc pri mojej praci.  Bohuzial mi ale niektore casti nefunguju. Pouzivam Win11 a pri otvarani dostavam message : 

[BRCC32 Error] vypisKN.vrc(63): file not found: vypisKN_Icon.ico
[BRCC32 Error] vypisKN.vrc(66): file not found: 
Users\Public\Documents\Embarcadero\Studio\22.0\Styles\Windows11_Modern_Light.vsf

taktiez mi z nejakeho dôvodu nefunguje excel aj ked mam excel TLB

Potreboval by som poradit kde môze byt chyba. Bol by som Vám velmi vdacny za pomoc. Dakujem

**Comment by vitasrutek** [comment]
Dobrý den,
ta první chyba je odkaz na ikonu aplikace, doporučuji tedy dát buď nějakou vlastní nebo dát default v nastavení projektu v Delphi.
Druhá chyba je obdobného charakteru, je nastaveno Custom Style, které jsem zvolil z GetIt manageru. Také doporučuji zvolit Default Style na Windows.
![obrazek](https://github.com/vitasrutek/CUZK-scraper/assets/98422550/fc93b0de-b323-445e-ae92-41b83c7490c2)

Ten Excel musíte mít nějak nesprávně nastavený. Vím, že jsem s tím vždy po první instalaci bojoval. Doporučuji si nejprve zkusit zkompilovat nějaký příklad s prací s Excelem z internetu, abyste ověřil funkčnost Excel_TLB. Protože jinak to normálně frčí.
